config/routes.rb
FflLocator::Application.routes.draw do
  get '/', to: 'dealers#index'
  get '/dealers/near/:coordinates(/radius/:radius)(/limit/:limit)(/json/:json)', :constraints => {coordinates: /([^\/]+)/}, :controller => 'dealers', :action => 'find_near'
 get '/directory', to: 'dealers#directory'
  resources :dealers

end

app/models/dealer.rb
class Dealer < ActiveRecord::Base
  belongs_to :license
  attr_accessor :distance

  def self.within(radius, lat, lng, limit)
    math = "( 3959 * acos( cos( radians( #{ActiveRecord::Base.sanitize lat}) ) * cos( radians( lat ) ) * cos( radians( lng ) - radians( #{ActiveRecord::Base.sanitize lng}) ) + sin( radians( #{ActiveRecord::Base.sanitize lat}) ) * sin( radians( lat ) ) ) )"
    results_raw = ActiveRecord::Base.connection.execute(
      "SELECT id, #{math}
      AS distance
      from dealers
      where #{math}  < #{ActiveRecord::Base.sanitize radius}
      ORDER BY distance limit  #{ActiveRecord::Base.sanitize limit};")
    results_raw.map do |row|
      dealer = Dealer.find_by_id(row["id"])
      dealer.distance = row["distance"]
      dealer
    end
  end

  def business_name
    if self[:business_name] == "null"
      return self[:license_name]
    else
      return self[:business_name]
    end
  end

end

app/models/license.rb
class License < ActiveRecord::Base
  has_many :dealers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  before_action :set_dealer, only: [:show, :edit, :update, :destroy]

  # GET /dealers
  # GET /dealers.json
  def directory
    @dealers = Dealer.page(params[:page])
    @coordinates = cookies[:coordinates]
    puts @coordinates
  end

  # GET /dealers/1
  # GET /dealers/1.json
  def show
  end

  # GET /dealers/new
  def new
    @dealer = Dealer.new
  end

  # GET /dealers/1/edit
  def edit
  end

  # POST /dealers
  # POST /dealers.json
  def create
    @dealer = Dealer.new(dealer_params)

    respond_to do |format|
      if @dealer.save
        format.html { redirect_to @dealer, notice: 'Dealer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dealer }
      else
        format.html { render action: 'new' }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealers/1
  # PATCH/PUT /dealers/1.json
  def update
    respond_to do |format|
      if @dealer.update(dealer_params)
        format.html { redirect_to @dealer, notice: 'Dealer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealers/1
  # DELETE /dealers/1.json
  def destroy
    @dealer.destroy
    respond_to do |format|
      format.html { redirect_to dealers_url }
      format.json { head :no_content }
    end
  end

  def near

  end

  def find_near
    if params[:radius].blank?
      params[:radius] = 45
    end
    if params[:limit].blank?
      params[:limit] = 25
    end
    @lat, @lng = params[:coordinates].split(",")
    @dealers = Dealer.within(params[:radius], @lat, @lng, params[:limit])
    if params[:json]
     render action: "find_near.json.jbuilder"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealer
      @dealer = Dealer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dealer_params
      params.permit(:license_id, :license_name, :business_name, :street, :state, :zip_code, :coordinates, :page, :radius, :limit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dealers/_form.html.erb
<%= form_for(@dealer) do |f| %>
  <% if @dealer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dealer.errors.count, "error") %> prohibited this dealer from being saved:</h2>

      <ul>
      <% @dealer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :license_id %><br>
    <%= f.number_field :license_id %>
  </div>
  <div class="field">
    <%= f.label :license_name %><br>
    <%= f.text_field :license_name %>
  </div>
  <div class="field">
    <%= f.label :business_name %><br>
    <%= f.text_field :business_name %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.number_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dealers/_list_dealers.erb
<div class="span12">

<table class="table table-striped">
  <thead>
    <tr>
      <th>license type</th>
      <th>license name</th>
      <th>Business name</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Phone</th>
      <th>Lat</th>
      <th>lng</th>
      <th>Distance (Miles)</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody >
    <% @dealers.each do |dealer| %>
      <tr>
        <td><%= dealer.license_id %></a></td>
        <td><%= dealer.license_name %></td>
        <td><%= dealer.business_name %></td>
        <td><%= dealer.street %></td>
        <td><%= dealer.city %></td>

        <td><%= dealer.state %></td>

        <td><%= number_with_precision(dealer.zip_code , precision: 0) %></td>
        <td><%= number_to_phone dealer.phone, area_code: true %></td>

        <td><%= number_with_precision(dealer.lat , precision: 4)%></td>
        <td><%= number_with_precision(dealer.lng , precision: 4)%></td>
        <td><%= number_with_precision(dealer.distance, precision: 2) %></td>
        <td><%= link_to 'Show', dealer %></td>
        <td><%= link_to 'Edit', edit_dealer_path(dealer) %></td>
        <td><%= link_to 'Destroy', dealer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/dealers/directory.html.erb
<h1>Listing dealers</h1>
<div class="near_location">
  <%- if @coordinates.nil? %>
<script>
  getGeoLocation();
</script>
<%- else %>
  <form class="server" action="/dealers/near/<%= @coordinates %>">
    <button class="btn">Find Dealers near you</button>
  </form>
<%- end %>
</div>

<%= render 'list_dealers' %>

<br>

<%= link_to 'New Dealer', new_dealer_path %>


 <%= paginate @dealers %>

app/views/dealers/edit.html.erb
<h1>Editing dealer</h1>

<%= render 'form' %>

<%= link_to 'Show', @dealer %> |
<%= link_to 'Back', dealers_path %>

app/views/dealers/find_near.html.erb
<h1>Near Locations</h1>
<h3><%= "(#{@lat}, #{@lng})" %></h3>

<%= render 'list_dealers' %>


<br>

app/views/dealers/index.html.erb
 <div id="store-locator-container" class="span8 offset2">
      <div id="page-header">

      <div id="form-container" >
        <form id="user-location" method="post" action="#" >
          <fieldset>
              <label for="address">Enter Address or Zip Code:</label>
              <input type="text" id="address" name="address" />

            <button class='btn' id="submit" name="submit">Submit</button>
          <fieldset>
        </form>
      </div>

      <div id="map-container">
        <div id="loc-list">
            <ul id="list"></ul>
        </div>
        <div id="map"></div>
      </div>
    </div>

    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
      <script>
        $(function() {
          $('#map-container').storeLocator();
        });
      </script>

app/views/dealers/new.html.erb
<h1>New dealer</h1>

<%= render 'form' %>

<%= link_to 'Back', dealers_path %>

app/views/dealers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>license type:</strong>
  <%= @dealer.license_id %>
</p>

<p>
  <strong>license name:</strong>
  <%= @dealer.license_name %>
</p>

<p>
  <strong>Business name:</strong>
  <%= @dealer.business_name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @dealer.street %>
</p>

<p>
  <strong>State:</strong>
  <%= @dealer.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @dealer.zip_code %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @dealer.lat %>
</p>

<p>
  <strong>lng:</strong>
  <%= @dealer.lng %>
</p>

<%= link_to 'Edit', edit_dealer_path(@dealer) %> |
<%= link_to 'Back', dealers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FflLocator</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">

      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">Federal Firearms License Directory</a>

      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>

    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row-fluid">

      <%= yield %>

  </div>


<div class="navbar navbar-fixed-bottom">
  <p class="navbar-text">

  </p>

</div>
</div>
<div class="navbar navbar-fixed-bottom">
  <div class="navbar-inner">


  <a href="http://dustinzeisler.com">Made by Dustin Zeisler</a> |
    <a href="https://github.com/zeisler/ffl_locator">Fork on Github</a>
    </div>
</div>

</body>
</html>